name: Bump version and Tag
description: This Action will bump a version tag
runs:
  using: 'docker'
  image: 'Dockerfile'
# for additional options, see: https://help.github.com/en/articles/metadata-syntax-for-github-actions
