---
name: Push workflow for release branches

on:
  push:
    branches:
      - 'master'

env:
  GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}

jobs:
  build-and-push:
    name: Bump and Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bump and Tag
        id: bump_and_tag
        uses: konsentus/action.bump-version-and-tag@master
        with:
          prefix: 'v'

      - name: Configure Git
        run: |
          git config user.email "$(git show -s --format=%ae)"
          git config user.name "$(git show -s --format=%an)"

      - uses: kellyselden/move-semver-tags-action@v2
